`timescale 1ns / 1ps
// =============================================================================
// tb_top.v  —  MNIST CNN Inference Testbench
// =============================================================================
//
// Tests N_IMAGES test images sequentially (default 10: one balanced sample
// per digit 0-9, so every class is exercised at least once).
//
// NOTE on the UART image loader: images are received through a real serial
// receiver in fabric (uart_rx_module.v). Behaviorally simulating a
// bit-banged 125000-baud serial transfer would be extremely slow in xsim
// (784 bytes x ~80us/byte), so this testbench injects
// test images directly into fmap0 via hierarchical reference and forces the
// DUT's internal `image_ready` flag high, bypassing the real serial line
// entirely. This validates the CNN datapath itself, not the UART receiver
// (which can only be verified on real hardware / with the RPi). BTN1 keeps
// its full, real function — only the "how does fmap0 get its data" step is
// bypassed.
//
// For each image:
//   1. Load test image (.mem) into DUT's fmap0 via hierarchical reference
//   2. Force image_ready high (stand-in for "a full image has arrived")
//   3. Pulse BTN1 to start inference, same as real hardware
//   4. Wait for LD5 (result ready)
//   5. Compare led[3:0] with the expected label (from labels.mem)
//
// Required files (generated by train.py, placed in test_images/):
//   img_000_input.mem ... img_099_input.mem   — pixel values, 784 lines, hex
//   labels.mem                                 — one hex digit (0-9) per line
//
// Required files (generated by train.py, placed in coe_files/):
//   conv2d_int8_weights.mem, conv2d_int8_bias.mem
//   conv2d_1_int8_weights.mem, conv2d_1_int8_bias.mem
//   dense_int8_weights.mem,   dense_int8_bias.mem
//   dense_1_int8_weights.mem, dense_1_int8_bias.mem
//
// Vivado: add this file as a simulation source. Set simulation working
// directory to the project root so relative paths resolve correctly.
//
// Estimated simulation time: ~500,000 cycles per image (serial architecture).
// =============================================================================

module tb_top;

// ---------------------------------------------------------------------------
// Clock: 125 MHz  (Arty Z7 XTAL -> MMCM -> fabric clock)
// ---------------------------------------------------------------------------
localparam CLK_PERIOD = 8;  // ns
localparam N_IMAGES   = 10;

reg clk, btn0, btn1;
wire [5:0] led;

// ---------------------------------------------------------------------------
// DUT
// -----------------------------------------------------------------------------
// uart_rx is tied idle-high (no real serial traffic is driven in simulation
// — see note above on why the UART path itself is bypassed here).
// ---------------------------------------------------------------------------
top_module u_top (
    .clk     (clk),
    .btn0    (btn0),
    .btn1    (btn1),
    .led     (led),
    .uart_rx (1'b1)
);

// ---------------------------------------------------------------------------
// Clock
// ---------------------------------------------------------------------------
initial clk = 0;
always #(CLK_PERIOD / 2) clk = ~clk;

// ---------------------------------------------------------------------------
// Expected labels — one hex digit per line, loaded from test_images/labels.mem
// (order matches img_000..img_099 generated by train.py)
// ---------------------------------------------------------------------------
reg [3:0] expected [0:N_IMAGES-1];
initial $readmemh("labels.mem", expected);

// ---------------------------------------------------------------------------
// Temporary image buffer (load from .mem, then copy to DUT)
// ---------------------------------------------------------------------------
reg [7:0] img_buf [0:783];

// ---------------------------------------------------------------------------
// Tasks
// ---------------------------------------------------------------------------

// Apply synchronous reset for 10 cycles
task do_reset;
    integer k;
    begin
        btn0 = 1'b1; btn1 = 1'b0;
        repeat (10) @(posedge clk);
        @(negedge clk); btn0 = 1'b0;
        repeat (2)  @(posedge clk);
    end
endtask

// Copy img_buf into DUT's image buffer via hierarchical reference
task copy_image_to_dut;
    integer j;
    begin
        for (j = 0; j < 784; j = j + 1)
            u_top.fmap0[j] = $signed(img_buf[j]);
    end
endtask

// Stand-in for "an image has arrived over UART": force image_ready
// permanently high once, and never release it. Verilog `release` reverts a
// signal to whatever its normal procedural logic last actually assigned —
// since top_module.v's always block only ever assigns image_ready inside
// `if (img_byte_we ...)` / `if (img_done)` branches that never fire in this
// bypass, releasing after only one cycle snaps it straight back to 0 (its
// last real, pre-force value), silently undoing the force before BTN1 is
// even pressed. Keeping it forced for the rest of the simulation sidesteps
// this entirely — correct for this bypass since the real UART path isn't
// being exercised here anyway.
//
// Timed to the DUT's actual internal clock (u_top.clk_pl, 40 MHz, generated
// by clk_wiz_0) rather than this testbench's own clk (raw 125 MHz board
// clock fed into the Clocking Wizard) — those two clocks run at different,
// unrelated phases/periods.
task mark_image_ready;
    begin
        @(negedge u_top.clk_pl);
        force u_top.image_ready = 1'b1;
    end
endtask

// Real BTN1 press, same mechanism real hardware uses — held for one clk_pl
// period so the DUT's btn1_r edge-detect register reliably samples it.
task press_btn1;
    begin
        // Defense in depth: re-check rst right here too, not just after
        // do_reset earlier in the sequence — if pll_locked dips again after
        // its initial lock (seen in behavioral sim: rst going back to 1
        // between "Reset complete" and the button press), rst_async can
        // re-assert and jam btn1_r at 0 for the whole press, silently
        // swallowing this pulse just like the original bug.
        while (u_top.rst) @(posedge u_top.clk_pl);
        @(negedge u_top.clk_pl);
        btn1 = 1'b1;
        @(posedge u_top.clk_pl);
        @(negedge u_top.clk_pl);
        btn1 = 1'b0;
    end
endtask

// Wait for LD5 (result ready); timeout after MAX_CYCLES
//
// Counts posedge u_top.clk_pl (the DUT's actual internal 40 MHz clock), not
// this testbench's own clk (raw 125 MHz board clock feeding the DUT's
// Clocking Wizard). The 800,000-cycle budget was sized for the CNN
// pipeline's real cycle count, which only makes sense measured against the
// clock the pipeline logic actually runs on.
task wait_for_result;
    output reg timed_out;
    integer cnt;
    begin
        timed_out = 1'b0;
        cnt = 0;
        while (!led[5] && cnt < 800_000) begin
            @(posedge u_top.clk_pl);
            cnt = cnt + 1;
        end
        if (cnt >= 800_000) begin
            $display("  [TIMEOUT] Inference did not complete within 800 000 cycles.");
            timed_out = 1'b1;
        end
    end
endtask

// ---------------------------------------------------------------------------
// Main test sequence
// ---------------------------------------------------------------------------
integer img_idx, errors;
reg     timed_out;
reg [8*32-1:0] fname;   // dynamic filename buffer

initial begin
    $display("");
    $display("=========================================");
    $display("  MNIST CNN Inference Testbench  (%0d images)", N_IMAGES);
    $display("=========================================");

    btn0 = 1'b0; btn1 = 1'b0;
    errors = 0;

    // Initial reset
    do_reset;

    // Wait for the internal reset to actually release. This must be judged
    // on u_top.rst itself (via clk_pl), not just u_top.pll_locked via this
    // testbench's own raw clk: rst_async = btn0 | ~pll_locked clears as soon
    // as pll_locked rises, but rst is the OUTPUT of a 2-FF synchronizer
    // running on clk_pl (see top_module.v rst_sync), which takes 2 more
    // clk_pl cycles (~50 ns) after that to fully deassert. Proceeding as
    // soon as pll_locked rises (checked on the much faster raw clk) races
    // ahead of that synchronizer: BTN1 can then get pressed while u_top.rst
    // is still 1, which holds btn1_r at 0 and swallows the pulse entirely
    // (btn1_pulse = btn1 & ~btn1_r never fires) once btn1 drops back to 0
    // the following cycle — this was silently eating every BTN1 press.
    while (u_top.rst) @(posedge u_top.clk_pl);
    $display("[%8t ns] Reset complete.", $time);
    $display("");

    // Force image_ready high once, for the whole run (see task comment).
    mark_image_ready;

    for (img_idx = 0; img_idx < N_IMAGES; img_idx = img_idx + 1) begin

        // ── Load test image ──────────────────────────────────────────────
        $sformat(fname, "img_%03d_input.mem", img_idx);
        $readmemh(fname, img_buf);

        copy_image_to_dut;

        $display("[%8t ns] Testing img_%03d (expected=%0d) ...",
                  $time, img_idx, expected[img_idx]);

        // ── Start inference (image_ready already forced high, see above) ──
        press_btn1;

        // LD4 should assert immediately. Checked on u_top.clk_pl (the clock
        // that actually drives r_inference_run), not this testbench's own
        // raw clk — clk_pl's period is ~3x longer, so checking on the raw
        // clk right after press_btn1 samples led[4] before the DUT's own
        // clk_pl edge that sets it has even happened yet.
        @(posedge u_top.clk_pl);
        if (!led[4])
            $display("  NOTE: LD4 (inference_run) did not assert as expected.");

        // ── Wait for done ────────────────────────────────────────────────
        wait_for_result(timed_out);

        // ── Check result ─────────────────────────────────────────────────
        if (!timed_out) begin
            if (led[3:0] === expected[img_idx]) begin
                $display("  PASS  predicted=%0d  expected=%0d",
                         led[3:0], expected[img_idx]);
            end else begin
                $display("  FAIL  predicted=%0d  expected=%0d",
                         led[3:0], expected[img_idx]);
                errors = errors + 1;
            end
        end else begin
            errors = errors + 1;
        end

        $display("");

        // Short pause, then reset before next image. Wait for u_top.rst to
        // actually release (clk_pl-timed) before the next iteration presses
        // BTN1 again — same synchronizer-latency race as the initial reset
        // above, and do_reset's own 2-cycle tail (on the raw, faster clk)
        // isn't enough to cover it.
        repeat (20) @(posedge clk);
        do_reset;
        while (u_top.rst) @(posedge u_top.clk_pl);
    end

    // ── Summary ──────────────────────────────────────────────────────────────
    $display("=========================================");
    if (errors == 0)
        $display("  ALL TESTS PASSED (%0d / %0d)  ✓", N_IMAGES, N_IMAGES);
    else
        $display("  FAILED: %0d / %0d test(s) did not pass.", errors, N_IMAGES);
    $display("=========================================");
    $display("");

    $finish;
end

// ---------------------------------------------------------------------------
// Global watchdog (prevents infinite hang if pipeline stalls)
// ---------------------------------------------------------------------------
initial begin
    // N_IMAGES x 800 000 cycles x clk_pl period (25 ns, the clock the CNN
    // pipeline actually runs on) + generous margin. Was CLK_PERIOD (this
    // testbench's raw 8 ns clk) before clk_wiz_0 made clk_pl the pipeline's
    // real clock — that stale reference underestimated the time budget.
    #(N_IMAGES * 800_000 * 25 * 2);
    $display("[WATCHDOG] Simulation exceeded maximum allowed time. Aborting.");
    $finish;
end

// ---------------------------------------------------------------------------
// Waveform dump (open in Vivado Simulator or GTKWave)
// ---------------------------------------------------------------------------
initial begin
    $dumpfile("tb_top.vcd");
    $dumpvars(0, tb_top);
end

endmodule
